# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: kissyyy  # Ex: registry.ng.bluemix.net/mynamespace
  pullPolicy: Always
